//
//  Workspace.swift
//  TradernetManifests
//
//  Created by Vitalii Sosin on 30.09.2024.
//

import ProjectDescription

let workspace = Workspace(
  name: "Tradernet",
  projects: ["."],
  generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
